name: refactors-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint code
      run: |
        pylint refactors/ tests/
    - name: Check documentation style
      run: |
        pydocstyle refactors/
    - name: Check format with black
      run: |
        black --check refactors/ tests/
    - name: Test with pytest
      run: |
        pytest tests --cov=refactors --cov-report=xml:./coverage.xml
    # - name: Fetch master for coverage diff
    #   run: |
    #     git fetch --no-tags --prune origin master
    # - name: Check coverage
    #   run: |
    #     diff-cover ./coverage.xml --compare-branch=origin/master --fail-under=100 --diff-range-notation '..'
